spring:
  datasource:
   url: jdbc:mysql://localhost:3306/file?characterEncoding=UTF-8&serverTimezone=UTC
   username: root
   password: cheese
   driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true    hibernate:      ddl-auto: update    properties:
      hibernate:
        format_sql: true
        